### ISSUE TITLE
如何在本地打開之？

### ISSUE THREAD

**Issue by CGLemon** [chengr4/jungo-web#3]
你好，我一直想在自己的電腦上打開它，但我不太清楚要怎使用，直接用 chromium 打開 index.html 會有以下錯誤，如下圖（我的 OS 是 Ubuntu）。謝謝！

![Screenshot from 2022-08-23 02-59-42](https://user-images.githubusercontent.com/39462842/185998271-1e7361a9-5695-457f-b2d4-fdb06f309cb9.png)

**Comment by chengr4** [comment]
你好，非常感謝你的問題。
這個問題是因為需要在 local 啟用一個 web server ，我平常都是用 vscode 的 `live server` extension 來解決
我剛剛上網找了一下可以用以下方式解決
> 前提是要載 nodejs
```
cd jungo-web
npx http-server .
```
然後用 browser 打開 `http://127.0.0.1:8080` (default)
或者你想用 python 可以參照這篇 https://stackoverflow.com/a/21608670/18536885

如果問題解決了再麻煩跟我說，謝謝

**Comment by CGLemon** [comment]
你好，python 方案和 nodejs 方案都試過了，兩者皆可以正常執行。

**Comment by chengr4** [comment]
非常感謝，我有空再去更新一下 readme
